### ISSUE TITLE
[Feature Request] Settings page for editor

### ISSUE THREAD

**Issue by Pipe-Runner** [dopplr-labs/dopplr-client#7]
Follow this https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html for option list.

**Comment by Pipe-Runner** [comment]
![photo_2020-11-24_14-08-32](https://user-images.githubusercontent.com/19551058/100069392-b5fd1e00-2e5e-11eb-887a-7d6d14e5271a.jpg)

**Comment by hnagrath09** [comment]
<img width="1792" alt="Screenshot 2020-12-13 at 3 05 00 PM" src="https://user-images.githubusercontent.com/33781906/102008168-79954300-3ce3-11eb-9b4f-cb7c7181f795.png">
